name: multiplayer_games_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  share_plus: ^7.0.2
  cupertino_icons: ^1.0.2
  flame: ^1.6.0
  supabase_flutter: ^1.4.0
  uuid: ^3.0.7
  share: ^2.0.4
  social_share: ^2.3.1
  font_awesome_flutter:
  adaptive_action_sheet: ^2.0.2
  clipboard: ^0.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^5.0.0
  rive: ^0.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
